export { default as Home } from './Home'
export { default as About } from './About'
export { default as Work } from './Work'
export { default as Skills } from './Skills'
export { default as Experience } from './Experience'
export { default as NotFound } from './NotFound'